name: babeetown
favicon: null
layout_spectrum: 0.2076224642805755
typography_spectrum: 0.7347663023974746
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.2628481991123408
  lightness: 0.22454996639862657
  saturation: 0.2451145756058395
  rhythmicContrast: 0.8101648245938122
purpose: []
