favicon: null
name: babeetown
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
purpose: []
color:
  saturation: 0.4398496
  lightness: 0.5494092
  brandStrength: 0.9489796
  brandColors:
    - '#FFFFFF'
    - '#F9D0AA'
    - '#1F0302'
    - '#A4DFE8'
    - '#6EBC94'
  rhythmicContrast: 0.5042965
typography_spectrum: 0.434479
layout_spectrum: 0.188507
analytics:
  twitter: null
  google: null
  facebook: null
cta:
  bucket: null
  version: null
  domain: null
