name: BABEETOWN
favicon: null
layout_spectrum: 0.50904
typography_spectrum: 0.49815
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: 'Designer fashion for infant, toddlers and children '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FFFFFF'
    - '#F9D0AA'
    - '#1F0302'
    - '#A4DFE8'
    - '#6EBC94'
  brandStrength: 0.5440387
  lightness: 0.5625
  saturation: 0.4398496
  rhythmicContrast: 0.5042965
purpose: []
