name: BABEETOWN
favicon: null
layout_spectrum: 1
typography_spectrum: 0.61732
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: Children Apparel and Toys. Direct from Korea.
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#f69576'
    - '#936546'
    - '#6eba95'
    - '#0f96c4'
  brandStrength: 0.5
  lightness: 0.625
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
